basePath: /
definitions:
  models.GlobalTokenWhitelist:
    properties:
      address:
        type: string
      blockNumber:
        description: blockNumber bigint,
        type: integer
      createdAt:
        type: string
      date:
        type: string
      id:
        type: integer
      tx:
        description: tx character varying(255),
        type: string
      updatedAt:
        type: string
    type: object
  models.Pool:
    properties:
      basicTokenAdr:
        type: string
      basicTokenDecimals:
        type: integer
      basicTokenSymbol:
        type: string
      blockNumber:
        description: blockNumber bigint,
        type: integer
      createdAt:
        type: string
      creatorAdr:
        type: string
      date:
        type: string
      decimals:
        type: integer
      dexeCommissionDen:
        type: integer
      dexeCommissionNum:
        type: integer
      id:
        type: integer
      investorCommissionDen:
        type: integer
      investorCommissionNum:
        type: integer
      investorRestricted:
        type: boolean
      isActualOn:
        type: boolean
      name:
        type: string
      poolAdr:
        type: string
      symbol:
        type: string
      totalSupply:
        type: string
      traderCommissionDen:
        type: integer
      traderCommissionNum:
        type: integer
      tx:
        description: tx character varying(255),
        type: string
      updatedAt:
        type: string
    type: object
  models.PoolTransfer:
    properties:
      amount:
        type: string
      blockNumber:
        description: blockNumber bigint,
        type: integer
      createdAt:
        type: string
      date:
        type: string
      id:
        type: integer
      poolAdr:
        type: string
      tx:
        description: tx character varying(255),
        type: string
      type:
        description: enum('deposit', 'withdraw')
        type: string
      updatedAt:
        type: string
      wallet:
        type: string
    type: object
  models.User:
    properties:
      avatar:
        type: string
      createdAt:
        type: string
      id:
        type: integer
      nickname:
        type: string
      updatedAt:
        type: string
      wallet:
        type: string
    type: object
  response.E:
    properties:
      code:
        type: integer
      context:
        type: object
      message:
        type: string
    type: object
  response.S:
    properties:
      data:
        type: object
      datetime:
        type: string
    type: object
  service_routes.GetNonceResponse:
    properties:
      nonce:
        type: integer
    type: object
  service_routes.PoolInfoResponse:
    properties:
      basicTokenAdr:
        type: string
      basicTokenDecimal:
        type: integer
      basicTokenSymbol:
        type: string
      copiers:
        type: number
      currentPrice:
        type: string
      fund:
        type: integer
      priceChange24H:
        type: number
      profitAndLoss:
        type: string
      symbol:
        type: string
      totalValueLocked:
        type: string
    type: object
  service_routes.responseTrade:
    properties:
      amountIn:
        type: string
      amountOutMin:
        type: string
      blockNumber:
        type: integer
      createdAt:
        type: string
      date:
        type: string
      deadline:
        type: string
      id:
        type: integer
      path:
        items:
          type: string
        type: array
      traderPool:
        type: string
      tx:
        type: string
      updatedAt:
        type: string
    type: object
info:
  contact: {}
  description: Dexe Investing Api
  title: Dexe Investing Api
  version: "1.0"
paths:
  /info/global-token-whitelist:
    get:
      consumes:
      - application/json
      description: Get Global Token Whitelist
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.S'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.GlobalTokenWhitelist'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.E'
      summary: Get Global Token Whitelist
      tags:
      - Info
  /nonce/{wallet}:
    get:
      consumes:
      - application/json
      description: Get Sign Nonce
      parameters:
      - description: User wallet address
        in: path
        name: wallet
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.S'
            - properties:
                data:
                  $ref: '#/definitions/service_routes.GetNonceResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.E'
      summary: Get Sign Nonce
      tags:
      - Nonce
  /pool-transfers/deposits/{wallet}:
    get:
      consumes:
      - application/json
      description: Get Deposits By Wallet
      parameters:
      - description: Wallet Address
        in: path
        name: wallet
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.S'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.PoolTransfer'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.E'
      summary: Get Deposits By Wallet
      tags:
      - PoolTransfers
  /pool-transfers/withdrawals/{wallet}:
    get:
      consumes:
      - application/json
      description: Get Withdrawals By Wallet
      parameters:
      - description: Wallet Address
        in: path
        name: wallet
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.S'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.PoolTransfer'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.E'
      summary: Get Withdrawals By Wallet
      tags:
      - PoolTransfers
  /pools:
    get:
      consumes:
      - application/json
      description: Get All Trader Pools
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.S'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Pool'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.E'
      summary: Get All Trader Pools
      tags:
      - Pools
  /pools/{wallet}:
    get:
      consumes:
      - application/json
      description: Get Pools By Creator Wallet
      parameters:
      - description: Pool creator wallet
        in: path
        name: wallet
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.S'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Pool'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.E'
      summary: Get Pools By Creator Wallet
      tags:
      - Pools
  /trader/{poolAddress}/info:
    get:
      consumes:
      - application/json
      description: Get Trader/Pool info
      parameters:
      - description: Pool address
        in: path
        name: poolAddress
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.S'
            - properties:
                data:
                  $ref: '#/definitions/service_routes.PoolInfoResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.E'
      summary: Get Trader/Pool info
      tags:
      - Trader
  /trades/{traderPool}:
    get:
      consumes:
      - application/json
      description: Get Trades By PoolAdr
      parameters:
      - description: traderPool Address
        in: path
        name: traderPool
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.S'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/service_routes.responseTrade'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.E'
      summary: Get Trades By PoolAdr
      tags:
      - Trades
  /user/{wallet}:
    get:
      consumes:
      - application/json
      description: Get User Info
      parameters:
      - description: User wallet address
        in: path
        name: wallet
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.S'
            - properties:
                data:
                  $ref: '#/definitions/models.User'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.E'
      summary: Get User Info
      tags:
      - User
  /user/{wallet}/avatar:
    put:
      consumes:
      - multipart/form-data
      description: Update User Avatar [SIGN]
      parameters:
      - default: iQxX3slnRg
        description: An authorization header
        in: header
        name: x-morph
        required: true
        type: string
      - description: User wallet address
        in: path
        name: wallet
        required: true
        type: string
      - description: Body with image
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.S'
            - properties:
                data:
                  $ref: '#/definitions/models.User'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.E'
      summary: Update User Avatar [SIGN]
      tags:
      - User
  /user/{wallet}/nickname:
    put:
      consumes:
      - multipart/form-data
      description: Update User Nickname [SIGN]
      parameters:
      - default: iQxX3slnRg
        description: An authorization header
        in: header
        name: x-morph
        required: true
        type: string
      - description: User wallet address
        in: path
        name: wallet
        required: true
        type: string
      - description: New user nickname
        in: formData
        name: nickname
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.S'
            - properties:
                data:
                  $ref: '#/definitions/models.User'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.E'
      summary: Update User Nickname [SIGN]
      tags:
      - User
  /user/signup:
    post:
      consumes:
      - multipart/form-data
      description: User SignUp [SIGN]
      parameters:
      - default: iQxX3slnRg
        description: An authorization header
        in: header
        name: x-morph
        required: true
        type: string
      - description: User nickname
        in: formData
        name: nickname
        required: true
        type: string
      - description: User wallet
        in: formData
        name: wallet
        required: true
        type: string
      - description: Body with image
        in: formData
        name: file
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.S'
            - properties:
                data:
                  $ref: '#/definitions/models.User'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.E'
      summary: User SignUp [SIGN]
      tags:
      - User
swagger: "2.0"
